apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::621400796062:user/github-ecr
      username: github-ecr
      groups:
        - system:masters